'use client';
import React from 'react';
import { Monitor, Smartphone, Tablet } from 'lucide-react';
import { LandingPage, LandingPreviewMode } from '../../../types/landing';
import { getLandingBlockRegistry } from './blockRegistry';
import { useApp } from '../../../context/AppContext';
import { landingDesignStyle } from '../../../lib/landing/landingDesign';

interface Props { page: LandingPage; mode: LandingPreviewMode; selectedBlockId: string | null; onModeChange: (mode: LandingPreviewMode) => void; onSelectBlock: (id: string) => void; }
export default function LandingBuilderPreview({ page, mode, selectedBlockId, onModeChange, onSelectBlock }: Props) {
  const { products } = useApp(); const product = products.find((item) => item.id === page.primaryProductId) || null;
  const visibleBlocks = page.blocks.filter((block) => !block.hidden && (mode === 'mobile' ? block.mobileVisible !== false : block.desktopVisible !== false));
  const frame = mode === 'mobile' ? 'w-[390px]' : mode === 'tablet' ? 'w-[768px]' : 'w-full max-w-[1180px]';
  return <div className="flex h-full min-h-0 flex-col bg-[#161616]"><div className="flex shrink-0 items-center justify-between border-b border-white/10 px-3 py-2"><div><b className="text-[10px] uppercase text-white">Preview local</b><p className="text-[8px] text-gray-600">Không đọc Firestore</p></div><div className="flex border border-white/10 bg-black p-1">{([['desktop', Monitor], ['tablet', Tablet], ['mobile', Smartphone]] as const).map(([key, Icon]) => <button key={key} type="button" onClick={() => onModeChange(key)} className={`flex items-center gap-1 px-2 py-1.5 text-[9px] uppercase ${mode === key ? 'bg-gold-light text-black' : 'text-gray-500'}`}><Icon className="h-3.5 w-3.5" /><span className="hidden xl:inline">{key}</span></button>)}</div></div><div className="min-h-0 flex-1 overflow-auto p-3"><div style={landingDesignStyle(page)} data-button-style={page.design?.buttonStyle || 'solid'} className={`landing-root mx-auto min-h-full max-w-full overflow-hidden border border-white/10 shadow-2xl transition-all ${frame}`}>{!page.layout.hideHeader && <div className="flex h-14 items-center justify-between border-b border-white/10 bg-black px-5 text-white"><b className="text-xs tracking-[.2em] text-gold-light">XƯỞNG IN 3D</b><span className="text-[9px] uppercase text-gray-500">Landing Header</span></div>}{visibleBlocks.map((block) => { const registry = getLandingBlockRegistry(block.type); const Renderer = registry.Renderer; return <Renderer key={block.id} block={block} page={page} product={product} products={products} mode={mode} editorMode selected={block.id === selectedBlockId} onSelect={() => onSelectBlock(block.id)} />; })}{!visibleBlocks.length && <div className="flex min-h-80 items-center justify-center text-xs uppercase text-gray-600">Không có block phù hợp</div>}{!page.layout.hideFooter && <div className="border-t border-white/10 bg-black px-5 py-8 text-center text-[9px] uppercase text-gray-600">Landing Footer · Xưởng In 3D</div>}{page.layout.stickyMobileCta && mode === 'mobile' && <div className="sticky bottom-0 border-t border-white/10 bg-black/95 p-3"><a href="#dat-hang" className="landing-button block w-full py-3 text-center text-xs font-black uppercase">{page.productOverrides?.ctaLabel || 'Đặt hàng ngay'}</a></div>}</div></div></div>;
}
